
all:
  hosts:
    wordpress:
      ansible_host: yoursite.com # your server's IP address or domain
      ansible_private_key_file: # path to your identity file to authenticate, like ~/.ssh/id_rsa.pem
